# Generated by Django 4.2.23 on 2025-09-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
    ]
