# Generated by Django 4.2.23 on 2025-09-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hangarin', '0002_rename_decription_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='p_name',
            new_name='name',
        ),
    ]
